In [1]:
import numpy as np

### Sparse VAE results

In [3]:
l0s = [10., 5.]
l1s = [0.1, 0.01, 0.001]
splits = range(5)
configs = []
results = []
for i in splits:
    result = []
    for l0 in l0s:
        for l1 in l1s:
            if i==0:
                configs.append((l0, l1))
            fname = '../../out/peerread_small/spikeslab.' + str(i) + '.beta=1.0.row_norm=False.l0_l1=' + str((l0,l1)) + '.dim=100.npy'
            err = np.load(fname)[0]
            result.append(err)
    results.append(result)
results = np.array(results)

results.mean(axis=0), results.std(axis=0), configs

FileNotFoundError: [Errno 2] No such file or directory: '../out/peerread_small/spikeslab.0.beta=1.0.row_norm=False.l0_l1=(10.0, 0.1).dim=100.npy'

### VAE results

In [ ]:
l0=10.
l1=1.
betas=[1.0, 2.0, 4.0, 6.0, 8.0, 16.0]
splits = range(5)
results = []
for i in splits:
    result = []
    for beta in betas:
        fname = '../../out/peerread_small/vae.' + str(i) + '.beta=' + str(beta) + '.row_norm=False.l0_l1=' + str((l0,l1)) + '.dim=100.npy'
        err = np.load(fname)[0]
        result.append(err)
    results.append(result)
results = np.array(results)

results.mean(axis=0), results.std(axis=0)

### Variational sparse coding results

In [2]:
l0=5.0
l1=0.001
splits = range(5)
results = []
for i in splits:
    fname = '../../out/peerread_small/vsc.' + str(i) + '.beta=1.0.row_norm=False.l0_l1=' + str((l0,l1)) + '.dim=100.npy'
    err = np.load(fname)[0]
    results.append(err)
results = np.array(results)

results.mean(axis=0), results.std(axis=0)

(267.96454, 3.5315852)

### Intervened study

In [22]:
n = 5
sigmas = [0.5, 1.0, 3.0]
l0=5.0
l1=0.01
model = 'spikeslab'
dim = 50
row_norm=False
results = np.zeros((n, len(sigmas)))
for i in range(5):
    for j, s in enumerate(sigmas):
        fname = '../../out/intervened_n=5/' + str(i) + \
        '/sigma=' + str(s) + '/' + model + '.beta=1.0.row_norm=' + \
        str(row_norm) + '.l0_l1=' + str((l0,l1)) +'.dim='+ str(dim) + '.npy'
        err = np.load(fname)[0]
        results[i][j] = err
results.mean(axis=0), results.std(axis=0)

(array([52.43961792, 49.19519424, 48.58023453]),
 array([0.38340029, 0.29116238, 0.13913134]))

## Intervened holdout

In [15]:
sigmas = [0.5, 1.0]
l0s=[10., 5.]
l1s=[0.1, 0.01, 0.001]
model = 'spikeslab'
dim = 50
row_norm=False
results = []
configs=[]
for s in sigmas:
    result=[]
    for l0 in l0s:
        for l1 in l1s:
            fname = '../../out/intervened_holdout' + \
            '/sigma=' + str(s) + '/' + model + '.beta=1.0.row_norm=' + \
            str(row_norm) + '.l0_l1=' + str((l0,l1)) +'.dim='+ str(dim) + '.npy'
            err = np.load(fname)[0]
            result.append(err)
            if s == 0.5:
                configs.append((l0,l1))
    results.append(result)
results=np.array(results)
results, configs

(array([[45.464607, 46.43993 , 45.628506, 45.22461 , 45.088963, 45.30879 ],
        [47.00002 , 47.915714, 47.122128, 46.6851  , 46.48943 , 46.90759 ]],
       dtype=float32),
 [(10.0, 0.1),
  (10.0, 0.01),
  (10.0, 0.001),
  (5.0, 0.1),
  (5.0, 0.01),
  (5.0, 0.001)])

## VAE intervened

In [24]:
n = 5
sigmas = [0.5, 1.0, 3.0]
l0=5.0
l1=0.001
model = 'vae'
dim = 50
beta=2.0
row_norm=False
results = np.zeros((n, len(sigmas)))
for i in range(5):
    for j, s in enumerate(sigmas):
        fname = '../../out/intervened_n=5/' + str(i) + \
        '/sigma=' + str(s) + '/' + model + '.beta='+ str(beta) +'.row_norm=' + \
        str(row_norm) + '.l0_l1=' + str((l0,l1)) +'.dim='+ str(dim) + '.npy'
        err = np.load(fname)[0]
        results[i][j] = err
results.mean(axis=0), results.std(axis=0)

(array([54.66052704, 52.08698578, 50.98447495]),
 array([0.29741674, 0.22819724, 0.44469977]))

### Variational sparse coding intervened

In [3]:
n = 5
sigmas = [0.5, 1.0, 3.0]
l0=5.0
l1=0.001
model = 'vsc'
dim = 50
beta=1.0
row_norm=False
results = np.zeros((n, len(sigmas)))
for i in range(5):
    for j, s in enumerate(sigmas):
        fname = '../../out/intervened_n=5/' + str(i) + \
        '/sigma=' + str(s) + '/' + model + '.beta='+ str(beta) +'.row_norm=' + \
        str(row_norm) + '.l0_l1=' + str((l0,l1)) +'.dim='+ str(dim) + '.npy'
        err = np.load(fname)[0]
        results[i][j] = err
results.mean(axis=0), results.std(axis=0)

(array([59.44869919, 58.21847076, 56.28092728]),
 array([1.42730961, 1.04343979, 0.74513133]))